<?php
return [
    "Production"    => [
        "getSMSList"                    =>  34938,
        "sendSMS"                       =>  34941,
        "getValidationSMSStatus"        =>  34931,
        "getEmailInfo"                  =>  34935,
        "getPushNotificationStatusAll"  =>  34933,
        "getPushNotificationStatusSeen" =>  34939,
        "getEmailList"                  =>  34934,
        "pushNotificationByPeerId"      =>  34936,
        "getSMSStatus"                  =>  34929,
        "sendValidationSMS"             =>  34930,
        "sendEmail"                     =>  34932,
        "pushNotificationByAppId"       =>  34940,
        "getPushNotificationStatusReceived"=> 34937,
        "getPushNotificationList"       =>  34943,
    ],
    "Sandbox"    => [
        "getSMSList"                    =>  42402,
        "sendSMS"                       =>  42403,
        "getValidationSMSStatus"        =>  42404,
        "getEmailInfo"                  =>  42405,
        "getPushNotificationStatusAll"  =>  42406,
        "getPushNotificationStatusSeen" =>  42407,
        "getEmailList"                  =>  42409,
        "pushNotificationByPeerId"      =>  42410,
        "getSMSStatus"                  =>  42411,
        "sendValidationSMS"             =>  42412,
        "sendEmail"                     =>  42413,
        "pushNotificationByAppId"       =>  42414,
        "getPushNotificationStatusReceived"=> 42415,
        "getPushNotificationList"       =>  42430,
    ],
];